export const IMAGE_CDN_URL =
  "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/";
export const CROUSEL_IMAGE_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_520,h_520/";
export const RESTAURANT_MENU_URL =
  "https://www.swiggy.com/dapi/menu/v4/full?lat=27.8973944&lng=78.0880129&menuId=";

// export const SWIGGY_RESTAURANT_CDN_URL =
//   "https://www.swiggy.com/dapi/restaurants/list/v5?lat=27.8973944&lng=78.0880129&page_type=DESKTOP_WEB_LISTING";

export const SWIGGY_RESTAURANT_CDN_URL =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=26.49690&lng=80.32460&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING";
export const SITE_LOGO =
  "https://lh3.googleusercontent.com/Em7AHf7XBH_RtGfCBVXz9RH8SM_pHkj3xPP-yd3cRguY1_Jc8fmqgx6WxnvGVyPV5xs5gL3HCD0FCuv6Xo4CwoY6ak4";
export const restaurantList = [
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "73011",
      name: "KFC",
      uuid: "27ff4155-fe46-418e-9862-ab98953bf953",
      city: "22",
      area: "Anand Vihar Colony",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "bdcd233971b7c81bf77e1fa4471280eb",
      cuisines: ["American", "Snacks", "Biryani"],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 31,
      lastMileTravel: 6.2,
      slugs: { restaurant: "kfc-chukkuwala", city: "dehradun" },
      address: "Clock Tower, Chakrata road, Dehradun",
      veg: false,
      avgRating: "4.0",
      totalRatings: 5000,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "542132",
      name: "Domnik Pizza",
      uuid: "f2ee37f5-9ab0-4903-9420-6cae020b0a38",
      city: "22",
      area: "Majra Bansal Home",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "sboh9oor0cvp6ztsyhvj",
      cuisines: ["Pizzas", "Italian", "Fast Food", "Snacks", "Beverages"],
      costForTwo: 30000,
      costForTwoString: "₹300 FOR TWO",
      deliveryTime: 33,
      lastMileTravel: 0.6,
      slugs: { restaurant: "domnik-pizza", city: "dehradun" },
      address: "Patel Nagar, Dehradun",
      veg: false,
      avgRating: "3.8",
      totalRatings: 50,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "321517",
      name: "FOOD PLANET RESTAURANT",
      uuid: "899d5dd4-200a-48b2-a321-391bb9486ec2",
      city: "22",
      area: "Majra",
      totalRatingsString: "50+ ratings",
      cloudinaryImageId: "ykboewqeoxnne8fgrnui",
      cuisines: ["Indian", "Chinese", "Tandoor", "Thalis", "Fast Food"],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 25,
      lastMileTravel: 0.7,
      slugs: { restaurant: "food-planet", city: "dehradun" },
      address: "Chandra Parisar, Majra, Dehradun",
      veg: false,
      avgRating: "2.8",
      totalRatings: 50,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "311806",
      name: "Burger King",
      uuid: "162a4dc4-50de-452a-82cf-751e18ac9952",
      city: "22",
      area: "Anand Vihar Colony",
      totalRatingsString: "5000+ ratings",
      cloudinaryImageId: "iqh7ew5ldfgvpd5dpz60",
      cuisines: ["Burgers", "American"],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 39,
      lastMileTravel: 6.3,
      slugs: { restaurant: "burger-king", city: "dehradun" },
      address: "Chakrata Road, Dehradun",
      veg: false,
      avgRating: "4.2",
      totalRatings: 5000,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "132460",
      name: "Annapurna Andhra Mess",
      uuid: "c6460418-904b-4371-9e04-0ce8b1b46cae",
      city: "22",
      area: "Dehradun",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "zw4qx2szsy9kbszk9n3d",
      cuisines: ["South Indian", "Biryani", "North Indian"],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 25,
      lastMileTravel: 1.4,
      slugs: { restaurant: "annapurna-andhra-mess", city: "dehradun" },
      address: "Chandrabani Road, Dehradun",
      veg: false,
      avgRating: "4.1",
      totalRatings: 1000,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "445789",
      name: "Pizza Express",
      uuid: "b5e8dfb9-8a3c-4d2a-9a7d-d58297cce865",
      city: "22",
      area: "Dalanwala",
      totalRatingsString: "200+ ratings",
      cloudinaryImageId: "m1y45zbvi4uk1bz4cymd",
      cuisines: ["Italian", "Fast Food"],
      costForTwo: 40000,
      costForTwoString: "₹400 FOR TWO",
      deliveryTime: 30,
      lastMileTravel: 4.5,
      slugs: { restaurant: "pizza-express", city: "dehradun" },
      address: "Dalanwala, Dehradun",
      veg: true,
      avgRating: "4.5",
      totalRatings: 200,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "556123",
      name: "Biryani Junction",
      uuid: "a123fd45-d123-4eaa-912a-d4567c123567",
      city: "22",
      area: "Rajpur Road",
      totalRatingsString: "1000+ ratings",
      cloudinaryImageId: "vhnpz3qlvke8tqwtkyv3",
      cuisines: ["Indian", "Biryani", "Mughlai"],
      costForTwo: 50000,
      costForTwoString: "₹500 FOR TWO",
      deliveryTime: 28,
      lastMileTravel: 5.0,
      slugs: { restaurant: "biryani-junction", city: "dehradun" },
      address: "Rajpur Road, Dehradun",
      veg: false,
      avgRating: "4.3",
      totalRatings: 1000,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "789123",
      name: "Chai Sutta Bar",
      uuid: "c789d8df-abc1-4567-98b9-d123456789aa",
      city: "22",
      area: "Race Course",
      totalRatingsString: "800+ ratings",
      cloudinaryImageId: "b09d7eaefb1de31a585a80884c8393be",
      cuisines: ["Beverages", "Snacks"],
      costForTwo: 15000,
      costForTwoString: "₹150 FOR TWO",
      deliveryTime: 20,
      lastMileTravel: 2.5,
      slugs: { restaurant: "chai-sutta-bar", city: "dehradun" },
      address: "Race Course, Dehradun",
      veg: true,
      avgRating: "4.6",
      totalRatings: 800,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "654321",
      name: "Tandoori Flames",
      uuid: "f345d9d9-d987-456d-b123-c789654321f4",
      city: "22",
      area: "Vasant Vihar",
      totalRatingsString: "300+ ratings",
      cloudinaryImageId: "66907cc81fd6116635ac88746e405980",
      cuisines: ["Indian", "Tandoor"],
      costForTwo: 35000,
      costForTwoString: "₹350 FOR TWO",
      deliveryTime: 26,
      lastMileTravel: 3.0,
      slugs: { restaurant: "tandoori-flames", city: "dehradun" },
      address: "Vasant Vihar, Dehradun",
      veg: false,
      avgRating: "4.0",
      totalRatings: 300,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "876543",
      name: "The Bakery Hub",
      uuid: "g678d9d9-abc1-4567-d123-c987654321ff",
      city: "22",
      area: "Balliwala",
      totalRatingsString: "150+ ratings",
      cloudinaryImageId: "fcrfrn9qgwsxuas42cnp",
      cuisines: ["Bakery", "Desserts"],
      costForTwo: 25000,
      costForTwoString: "₹250 FOR TWO",
      deliveryTime: 18,
      lastMileTravel: 1.2,
      slugs: { restaurant: "the-bakery-hub", city: "dehradun" },
      address: "Balliwala, Dehradun",
      veg: true,
      avgRating: "4.3",
      totalRatings: 150,
    },
    subtype: "basic",
  },
  {
    type: "restaurant",
    data: {
      type: "F",
      id: "908123",
      name: "Waffle Delight",
      uuid: "h567d8df-abc1-4567-d789-f098765432a1",
      city: "22",
      area: "Rajpur Road",
      totalRatingsString: "100+ ratings",
      cloudinaryImageId: "eozerfua7ygpxho5wkao",
      cuisines: ["Desserts", "Beverages"],
      costForTwo: 20000,
      costForTwoString: "₹200 FOR TWO",
      deliveryTime: 22,
      lastMileTravel: 3.5,
      slugs: { restaurant: "waffle-delight", city: "dehradun" },
      address: "Rajpur Road, Dehradun",
      veg: true,
      avgRating: "4.4",
      totalRatings: 100,
    },
    subtype: "basic",
  },
  // Add 10 more restaurants similarly...
];
